@echo off
cd /d "%~dp0"
echo Stopping anything already on port 5173...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :5173 ^| findstr LISTENING') do taskkill /F /PID %%a >nul 2>&1
echo Installing dependencies...
call npm install
echo Starting frontend at http://localhost:5173 ...
call npm run dev
